### ISSUE TITLE
Math Support? 

### ISSUE THREAD

**Issue by njkrichardson** [aksakalli/jekyll-doc-theme#12]
How can we include math in our markdown files? My previous jekyll site used a simple {include math support.html}, but when I copy over the html file and use the command, math looks very wacky.

**Comment by aksakalli** [comment]
I am using [MathJax](https://www.mathjax.org/) in [my personal blog](https://github.com/aksakalli/aksakalli.github.io).

You only need to add MathJax in [_includes/js_files.html](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/_includes/js_files.html) as

```
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'></script>
```

Now you can use Tex style equations:

```
$$ x_i' = \sum_{j} A_{ij}x_j $$
```

**Comment by njkrichardson** [comment]
Thanks!
