### ISSUE TITLE
Customize CSS

### ISSUE THREAD

**Issue by taehyeok-jang** [aksakalli/jekyll-doc-theme#14]
Had trouble while customizing CSS. 

As the post (https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/) from Github Pages official explains how to, I followed it. But /assets/css/style.scss does not work. 

And I also tried to understand how default CSS codes are generated from bootstrap, bootswatch. There are many parts that seems to be related to generate CSS, especially at directory _sass/~~/_variable.scss. So I didn't have any idea where to insert inner structured SCSS code in those.

Can you guys give me the solution to simply customize my Github Pages? :)

**Comment by aksakalli** [comment]
have you checked the documentation for [themes](https://aksakalli.github.io/jekyll-doc-theme/docs/themes/) and [customization](https://aksakalli.github.io/jekyll-doc-theme/docs/customization/)?

If you just need to add a CSS line, you can add it to [css/main.scss](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/css/main.scss).

**Comment by taehyeok-jang** [comment]
oh, I passed the detail in the document even though I checked it.
thanks!
