### ISSUE TITLE
maybe add ".html" to /allposts

### ISSUE THREAD

**Issue by t-h-e** [aksakalli/jekyll-doc-theme#16]
I use nginx to run this website. I got a 404 error after setting it up and trying to access all blog posts through the link "All posts ..." in the blog, because it links to "https://your-domain.com/allposts" instead of "https://your-domain.com/allposts.html".

To solve this, you either have to add `.html` to `/allposts` in [_layouts/post.html line 15](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/_layouts/post.html#L15)

Or make nginx rewrite the url, which seems more complicated.

Thanks for providing this theme. I really like it 😃

**Comment by aksakalli** [comment]
you can have a look at the [nginx.con](https://github.com/aksakalli/jekyll-doc-theme/blob/50678a3d07d74f03d8d98574f129097f2bd55a61/nginx.conf) for solving this problem.
