### ISSUE TITLE
Latex support?

### ISSUE THREAD

**Issue by fmaussion** [aksakalli/jekyll-doc-theme#17]
Thanks for this great theme!

Is there a way to enable latex support in markdown? I've tried to use latex syntax without success, but I know it works well on other jekyll websites I'm maintaining.

**Comment by aksakalli** [comment]
Thank you for your kind words.

You can use [MathJax](https://www.mathjax.org/) for latex support like I use in [my personal blog](https://github.com/aksakalli/aksakalli.github.io/blob/master/_includes/js_files.html).

1. Just include MathJax in `jekyll-doc-theme/_includes/js_files.html` as 

```
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
```

2. Now you can use Latex formula in your markdown file between double dollar signs like:

```
$$ J(A,B) = \frac{|A \cap B|}{|A \cup B|} $$
```

**Comment by fmaussion** [comment]
Perfect! Works like a charm.
