### ISSUE TITLE
Change default font size

### ISSUE THREAD

**Issue by fmaussion** [aksakalli/jekyll-doc-theme#18]
I'd like to change two minimal default settings to this otherwise excellent theme (the best I've encoutered so far!). I find that the the layout of a doc page is quite dense, and I find the font-size too small ([here](https://transparency-lecture.github.io/docs/pull-request/) for example I used H4 titles in order not to have huge differences between titles and main text). Is there a relatively simple way to change two settings:
- default text fontsize
- space between text blocks or between titles and text blocks or between images and text blocks in order to make a less-dense imporession on the reader

I'm not very familiar with html or css, therefore my simple question (apologies!)

**Comment by aksakalli** [comment]
This theme uses [Sass](https://sass-lang.com) for rendering css styles, so you can change font variables and font sizes in this file for the `paper` theme:

https://github.com/aksakalli/jekyll-doc-theme/blob/f0bd01a4d324c7e43f8b9c5880071cefb969ec2c/_sass/bootswatch/paper/_variables.scss#L52-L61
