### ISSUE TITLE
Missing `<li>` tag in `docs_nav.html`

### ISSUE THREAD

**Issue by funkfinger** [aksakalli/jekyll-doc-theme#23]
There is a missing `<li>` tag in the `{% for item in section.docs %}` loop in `docs_nav.html` file.

I've fixed it in [my fork](https://github.com/funkfinger/jekyll-doc-theme) and can do a pull request if desired.

**Comment by aksakalli** [comment]
it should be `div` > `a` instead of `ul` > `li` fixed in 9401250

thank you for reporting! :+1:
