### ISSUE TITLE
Asset folders not copied when using remote-theme

### ISSUE THREAD

**Issue by kenjdavidson** [aksakalli/jekyll-doc-theme#37]
Whether it's the Jekyll or gh-pages version the current assets folders are not being copied when attempting to use `remote-theme: aksakalli/jekyll-doc-theme@gh-pages`.  I like the theme, but I don't want to clone the entire thing into my project to use it.

With some minor changes I was able to get it working with

`remote-theme: kenjdavidson/jekyll-doc-theme@gh-pages` 

and I'm curious if you'd be interested in those?   Or if it's something that you've looked into doing?

**Comment by kenjdavidson** [comment]
Hey I just saw you converted the assets to allow for gh-pages.  I hadn't submitted a pull request as I was still working on the other files:
- search.json
- allposts.html
- etc.

These files are not created when using the remote-theme: kenjdavidson/jekyll-doc-theme (and I'm assuming yours too).  I've tried adding them to the includes within config but that didn't work.  My next test was to add them to _pages/ and provide a permalink.

Maybe you can sort it out before I have a chance (which probably won't be until the weekend).

**Comment by aksakalli** [comment]
yes, with 61965fc the assets are included in the `_site`  as `remote_theme`. You are welcome to send PR if you can figure it out :)

**Comment by kenjdavidson** [comment]
After looking through the Jekyll and RemoteTheme it looks like it's working as intended.  From what I can tell the best way to do it as (as mentioned) move the extra pages to the assets/ folder and have them include the permalink in the front matter - Jekyll will add them to the regular pages[] when processing if done this way.  

One of the other things I did was split the current main.scss file into two:
- main.scss which contains the frontmatter processing and an @import _site
- _site.scss which contains all the non front matter styles

There is just less to copy/paste into my own main.scss, and means that you can change the _site.scss without affecting my own overrides.
