### ISSUE TITLE
US-ASCII

### ISSUE THREAD

**Issue by chraibi** [aksakalli/jekyll-doc-theme#4]
Trying to use this theme in my own Gitlab-instance I get the following error

```  
Liquid Exception: invalid byte sequence in US-ASCII in _layouts/redirect.html
```

I wonder where does this file come from?

**Comment by aksakalli** [comment]
Redirect pages are created by [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) plugin.
Using [another fixed version](https://github.com/jekyll/jekyll-redirect-from/issues/139#issuecomment-274398896) might solve the issue. You can change it in `Gemfile` like
```
group :jekyll_plugins do
   gem "jekyll-feed"
   gem "jekyll-sitemap"
   gem "jekyll-redirect-from", "0.10.0"
   gem "jekyll-seo-tag"
end
```

or could be an issue about the Gitlab build environment: this might able to solve it

```
image: ruby:2.3

before_script:
  - apt-get update >/dev/null
  - apt-get install -y locales >/dev/null
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
```

see [stackoverflow](https://stackoverflow.com/a/38316690/1418997)

**Comment by chraibi** [comment]
Problem solved. Thanks!

**Comment by aksakalli** [comment]
actually `Gemfile.lock` is already providing a fixed version for `jekyll-redirect-from`, more likely it is a problem about the environment.

**Comment by chraibi** [comment]
Yeah I think so. Your theme works just fine. I tested it locally.
[Here](https://gitlab.com/gitlab-org/gitlab-ce/issues/14983#note_4637913) someone had the same issue.
