### ISSUE TITLE
Where is main.css

### ISSUE THREAD

**Issue by AkiraVoid** [aksakalli/jekyll-doc-theme#42]
My browser want to find a file names main.css but in the assets folder, there's no such file. I just find main.scss but...
I cannot use this theme normally. Help me please. If you want check it by yourself please go to: [quickstage.org](https://quickstage.org)

**Comment by kenjdavidson** [comment]
Couple things:

1. Your version of main.scss has no front matter, and therefore isn't being converted to main.css
2. Your urls are being converted to `/Quickstage/assets/js/...` instead of `/assets/js/...`

Not really sure how that happened, as the current version has both of these correct.

**Comment by aksakalli** [comment]
hey, seems like you are using the root url, did you try to set `baseurl: "/"` ?

https://github.com/aksakalli/jekyll-doc-theme/blob/61965fc5e20b20f148a0910551149a6feded2a95/_config.yml#L9

**Comment by aksakalli** [comment]
oh, you are using the `docs` folder in [a repo](https://github.com/AkiraVoid/QuickStage/tree/master/docs). 

I would suggest you to follow these steps:

1. create an organisation `QuickStage`
2. create a repo `quickstage.github.io` in this organisation as:  https://github.com/QuickStage/quickstage.github.io
3. change `baseurl: "/"`, delete `CNAME` file
4. push the code to the root folder of the master branch. Now you have https://quickstage.github.io serving your website.
5. make the `CNAME` configuration in your DNS and push the `CNAME` file to the master

**Comment by AkiraVoid** [comment]
Now I've set `baseurl` to `"/"`, and it seems that everything is ok but I still cannot find the main.css. Do I need to create a new account to create an organisation? It it quite troublesome and I don't want to remember another password. But if it's neccessary, I'll try it.

**Comment by AkiraVoid** [comment]
And you can access to [quickstage.org](https://quickstage.org) to learning the changes of my web.

**Comment by aksakalli** [comment]
> Now I've set `baseurl` to `"/"`, and it seems that everything is ok but I still cannot find the main.css. Do I need to create a new account to create an organisation? It it quite troublesome and I don't want to remember another password. But if it's neccessary, I'll try it.

No, you don't need to create a new account, just create it under your username using [this link](https://github.com/account/organizations/new?coupon=&plan=team_free)

**Comment by AkiraVoid** [comment]
I tried these steps but the question haven't be solved. You can see [this repo](https://github.com/QuickStage/quickstage.github.io). But when I access to [quickstage.org](https://quickstage.org), I still cannot find main.css... Do I just forget to do some settings to compile the main.scss?

**Comment by kenjdavidson** [comment]
Your main. Scss has no front matter. So it thinks it's a static file. Add empty front Matter to your file and it will "compile".

**Comment by AkiraVoid** [comment]
Well, thanks.
