### ISSUE TITLE
[search] Content Search feature

### ISSUE THREAD

**Issue by balamurugansanthanaraj** [aksakalli/jekyll-doc-theme#45]
Is it possible to get a content search feature instead of searching page name ?

**Comment by aksakalli** [comment]
It can be possible if you modify [search.json](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/assets/search.json) & [main.js](https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/assets/js/main.js) to include also "[page.content](https://jekyllrb.com/docs/variables/#page-variables)".
