### ISSUE TITLE
Serve jekyll-doc-theme/docs/ in root (/)

### ISSUE THREAD

**Issue by guzmo** [aksakalli/jekyll-doc-theme#7]
How would I do if I wanted to serve "jekyll-doc-theme/docs/" directly as root. I'm very new to jekyll and my google skillz didn't find anything.

**Comment by aksakalli** [comment]
you can just comment out `base_url` in `_config.yml`

https://github.com/aksakalli/jekyll-doc-theme/blob/gh-pages/_config.yml#L8

or assign empty string like: `baseurl: ""`

maybe I should have put this to _Getting Started_ guide
